//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudOpertionAPI.entityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewDemoEntities : DbContext
    {
        public NewDemoEntities()
            : base("name=NewDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<role_master> role_master { get; set; }
        public virtual DbSet<user_details> user_details { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
    }
}
